# length_in_x: 2.5
# length_in_y: 2.5
# position_x: 0.0
# position_y: 0.0
# resolution: 0.05
# min_variance: 0.000009
# max_variance: 0.01
# mahalanobis_distance_threshold: 2.5
# multi_height_noise: 0.0000009
length_in_x:                                6.0
length_in_y:                                6.0
position_x:                                 0.0
position_y:                                 0.0
resolution:                                 0.1
min_variance:                               0.0001
max_variance:                               0.05
mahalanobis_distance_threshold:             2.5
multi_height_noise:                         0.001
